In [2]:
import numpy as np

##Creating arrays using numpy
##Let's create a 1D array

arr1 = np.array([1,2,3,4]) ##np.array is a function wich will actually help us to create an array

In [3]:
print(arr1)

[1 2 3 4]


In [5]:
print(arr1.shape)

(4,)


In [10]:
arr2 = np.array([1,2,3,4])
arr2.reshape(1,4) ## here 1,4 basically means 1 row and 4 columns

array([[1, 2, 3, 4]])

In [14]:
##2D Arrays
arr2=np.array([[1,2,3,4],[2,3,4,5]])
arr2.shape

(2, 4)

In [15]:
print(arr2)

[[1 2 3 4]
 [2 3 4 5]]


In [23]:
##Lets create arrays with somme inbuilt function
arr = np.arange(0,10,2).reshape(5,1)
print(arr)


[[0]
 [2]
 [4]
 [6]
 [8]]


In [24]:
##Some inbuilt function in np
np.ones((3,4)) ##Creates a matrix of ones with 3 rows and 4 columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
##Creating an identity array
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
##Attributes of numpy array

##arr.shape - for shape of the array
##arr.ndim - for dimension of array
##arr.size - for size of the array
##arr.dtype - for datatype of the array##arr.itemsize - for itemsize of the array

In [31]:
## Numpy Vectorised Operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([2,3,4,5,6])

## Element wise Addition
print("Addition : ", arr1+arr2)

## Element wise Substraction
print("Substraction", arr1-arr2)

## Element wise Multiplication
print("Multiplication", arr1*arr2)

##Remember all the return type will also be an array

Addition :  [ 3  5  7  9 11]
Substraction [-1 -1 -1 -1 -1]
Multiplication [ 2  6 12 20 30]


In [35]:
## Universal function
arr = np.array([1,2,3,4,5])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [39]:
## Slciing operations

##Array slicing and Indexing
arr = np.array([[1,2,3,4],[3,4,5,6],[7,8,9,3]])
print("Array : \n", arr)

Array : 
 [[1 2 3 4]
 [3 4 5 6]
 [7 8 9 3]]


In [40]:
## How to access a single element from the array

## Lets say I wanna pick up 1

arr[0]

array([1, 2, 3, 4])

In [41]:
arr[0][0]

1

In [42]:
arr[1:]

array([[3, 4, 5, 6],
       [7, 8, 9, 3]])

In [45]:
arr[1:,2:]   ##To slice a matrix within a matrix

array([[5, 6],
       [9, 3]])

In [46]:
print(arr[1:,0:2])

[[3 4]
 [7 8]]


In [47]:
print(arr[0:2,2:])

[[3 4]
 [5 6]]


In [48]:
## Modify array elements

arr[0][0] = 100

In [49]:
print(arr)

[[100   2   3   4]
 [  3   4   5   6]
 [  7   8   9   3]]


In [50]:
arr[1:] = 200
print(arr)

[[100   2   3   4]
 [200 200 200 200]
 [200 200 200 200]]


In [52]:
## Practical Applications with respect to array

##Statistical concept - Normalization (changing data to have a mean of 0 and a astandard deviation of 1)

arr = np.array([1,3,4,5,2])

mean = np.mean(arr)
std = np.std(arr)

normalization = arr - mean/std
print("Normalized data : ", normalization)

## Mean, Median, Standard Deviation and Variance can be found in these ways


Normalized data :  [-1.12132034  0.87867966  1.87867966  2.87867966 -0.12132034]


In [53]:
## Logical Operations

arr = np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
arr>5 ## Give true if value is greater than 5 else it gives false
## to take data greater than 5 use indexing
arr[(arr>5) & (arr<9)] ##Logical and will work here

array([6, 7, 8])